linters:
  run:
    concurrency: 2
    skip-dirs:
      - tests/composefiles
  enable-all: false
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 200
  revive:
    confidence: 0.8
issues:
  # golangci hides some golint warnings (the warning about exported things
  # withtout documentation for example), this will make it show them anyway.
  exclude-use-default: false
  exclude:
    - should not use dot imports
